apiVersion: v1
kind: Pod
metadata:
  name: detas
spec:
  containers:
  - name: detas
    image: shovit23/detas:latest
    env:
      - name: MYSQL_DATABASE
        value: "detas"
      - name: MYSQL_USER
        value: "detas"
      - name: MYSQL_PASSWORD
        value: "detas"
      - name: MYSQL_ROOT_PASSWORD
        value: "root"
    ports:
    - containerPort: 3306

