apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    USE detas;
    CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) UNIQUE NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL);
    CREATE TABLE user_roles (id INT AUTO_INCREMENT PRIMARY KEY, userId INT NOT NULL, roleName VARCHAR(255) NOT NULL, FOREIGN KEY (userId) REFERENCES users(id));
    CREATE TABLE roles_list (id INT AUTO_INCREMENT PRIMARY KEY,roleName VARCHAR(255) UNIQUE NOT NULL);
    CREATE TABLE modules (id INT AUTO_INCREMENT PRIMARY KEY,moduleKey VARCHAR(255) UNIQUE NOT NULL,moduleName VARCHAR(255) UNIQUE NOT NULL,moduleDescription TEXT,moduleOwner VARCHAR(255),FOREIGN KEY (moduleOwner) REFERENCES users(email));
    CREATE TABLE services (serviceId INT AUTO_INCREMENT PRIMARY KEY,serviceName VARCHAR(255) UNIQUE NOT NULL,serviceDescription TEXT,moduleName VARCHAR(255) NOT NULL,FOREIGN KEY (moduleName) REFERENCES modules(moduleName));
    CREATE TABLE user_token (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,token VARCHAR(255) UNIQUE NOT NULL);
