apiVersion: v1
kind: Service
metadata:
  name: detas-service
spec:
  type: LoadBalancer
  selector:
    app: detas
  ports:
  - protocol: TCP
  - port: 80
    # By default and for convenience, the `targetPort` is set to
    # the same value as the `port` field.
    targetPort: 3000
