apiVersion: v1
kind: Pod
metadata:
  name: detas
spec:
  containers:
  - name: detas
    image: shovit23/detas:latest
    env:
      - name: DATABASE_URL
        value: "mysql://root:root@mysql:3306/detas"
    ports:
    - containerPort: 3000
